### ISSUE TITLE
API request failed with status 422

### ISSUE THREAD

**Issue by matheustav** [caddy-dns/spaceship#1]
Hi!
First of all, thanks for this awesome tool!

I'm trying to issue a cert for my domain, but I'm getting this errors (removed only the sensitive data):
```
{"level":"error","ts":1758380031.0555658,"msg":"cleaning up solver","identifier":"mydomain.com","challenge_type":"dns-01","error":"no memory of presenting a DNS record for \"_acme-challenge.mydomain.com\" (usually OK if presenting also failed)","stacktrace":"github.com/mholt/acmez/v3.(*Client).solveChallenges.func1\n\tgithub.com/mholt/acmez/v3@v3.1.2/client.go:318\ngithub.com/mholt/acmez/v3.(*Client).solveChallenges\n\tgithub.com/mholt/acmez/v3@v3.1.2/client.go:363\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.1.2/client.go:136\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.24.0/acmeissuer.go:489\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.24.0/acmeissuer.go:382\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.10.2/modules/caddytls/acmeissuer.go:288\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.24.0/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.24.0/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.24.0/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.24.0/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.24.0/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.24.0/async.go:73"}
{"level":"error","ts":1758380031.4185488,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"mydomain.com","issuer":"acme-v02.api.letsencrypt.org-directory","error":"[mydomain.com] solving challenges: presenting for challenge: adding temporary record for zone \"mydomain.com.\": failed to append records: API request failed with status 422: {\"detail\":\"The request is invalid.\",\"data\":[{\"field\":\"items\",\"details\":\"Value is \\\"null\\\" but should be \\\"array\\\".\"}]} (order=https://acme-v02.api.letsencrypt.org/acme/order/AAAAAAAA/XXXXXXXXXXX) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1758380031.4186213,"logger":"tls.obtain","msg":"will retry","error":"[mydomain.com] Obtain: [mydomain.com] solving challenges: presenting for challenge: adding temporary record for zone \"mydomain.com.\": failed to append records: API request failed with status 422: {\"detail\":\"The request is invalid.\",\"data\":[{\"field\":\"items\",\"details\":\"Value is \\\"null\\\" but should be \\\"array\\\".\"}]} (order=https://acme-v02.api.letsencrypt.org/acme/order/AAAAAAAA/XXXXXXXXXXX) (ca=https://acme-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":3.292113553,"max_duration":2592000}
```

Caddyfile
```
mydomain.com:443 {
	reverse_proxy web:6435

	tls {
		dns spaceship *API_KEY* *API_SECRET*
	}
}

```

Dockerfile
```
FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/caddy-dns/spaceship

FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Am I doing something wrong or is this a bug? 🤔 

Thanks!

**Comment by n2noon** [comment]
I'm also getting this

**Comment by pogman-code** [comment]
I have the same issue when using wildcards domains (*.foo.com), anyone found how to solve this?

**Comment by dolokolo** [comment]
This guy fixed it.

https://github.com/dippysan/caddy_dns_spaceship

**Comment by pogman-code** [comment]
That's nice but since it's not an official package, it can't be installed through `caddy add-package`.

I guess I'll use it with `xcaddy` until this is fixed here.

Thank! :)

**Comment by leon-ha** [comment]
And I got exactly the same message and I can't get a certificate for my domain by this caddy-dns_spaceship.

>This guy fixed it.
**dolokolo** 
Where did he fix it? Could you please show me, how to achieve this?

**Comment by dolokolo** [comment]
> And I got exactly the same message and I can't get a certificate for my domain by this caddy-dns_spaceship.
> 
> > This guy fixed it.
> > **dolokolo**
> > Where did he fix it? Could you please show me, how to achieve this?

Use this Dockerfile to build the container:
```
FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/dippysan/caddy_dns_spaceship

FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by leon-ha** [comment]
> Use this Dockerfile to build the container:
> 
> ```
> FROM caddy:2-builder AS builder
> RUN xcaddy build \
>     --with github.com/dippysan/caddy_dns_spaceship
> 
> FROM caddy:2
> COPY --from=builder /usr/bin/caddy /usr/bin/caddy
> ```
You are great. Thank you very much. It's working. :) I'm happy.

**Comment by empressmarissa** [comment]
This is an upstream issue in https://github.com/libdns/spaceship. I've made a pull request to fix it https://github.com/libdns/spaceship/pull/2

Let's hope the maintainer can review and merge this soon so we can use this package again

In the meanwhile you can also use this to build your caddy temporarily and easily get back to the original package when it's updated.

EDITED 25-05-2026: We now need to explicitly replace libdns/spaceship as well for this to fully work. I also updated both libdns and caddy-dns/spaceship to the latest versions in these releases.

```
FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/caddy-dns/spaceship=github.com/empressmarissa/caddy-dns-spaceship@v1.1.1 \
    --replace github.com/libdns/spaceship=github.com/empressmarissa/libdns_spaceship@v1.1.0

FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by yhmtsai** [comment]
I share my setup to include the changes from https://github.com/libdns/spaceship/pull/3 on libdns.
The following replaces libdns to the pull request branch. It clones the repo twice because caddy disallow to replace two sources by the same local folder.

```
FROM caddy:2-builder-alpine AS builder
RUN git clone -b pr/fix-acme-spaceship https://github.com/msch-nutrient/spaceship
RUN git clone -b pr/fix-acme-spaceship https://github.com/msch-nutrient/spaceship spaceship-2
RUN xcaddy build \
    --with github.com/caddy-dns/spaceship=github.com/empressmarissa/caddy-dns-spaceship@v1.0.0 \
    --with github.com/empressmarissa/libdns_spaceship=./spaceship \
    --with github.com/libdns/spaceship=./spaceship-2
FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by dolokolo** [comment]
For some reason, none of these builds are working for me now, and I'm getting 422 on all my requests. Anyone has any suggestions?
I tried building the image with all solutions posted in this thread.
```
{"level":"error","ts":1775482201.5980172,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"mysubdomain.mydomain.eu","issuer":"acme-v02.api.letsencrypt.org-directory","error":"[mysubdomain.mydomain.eu] solving challenges: presenting for challenge: adding temporary record for zone \"eu.\": failed to append records: API request failed with status 422: {\"detail\":\"The request is invalid.\",\"data\":[{\"field\":\"domain\",\"details\":\"The length of domain must meet the minimum required length.
``` 


Caddyfile looks like:
```
mysubdomain.mydomain.eu {
        tls {
                dns spaceship {
                        api_key myapikey
                        api_secret myapisecret
                }
                resolvers 8.8.8.8 8.8.4.4
        }
        reverse_proxy 192.168.1.123:1234
}
```

**Comment by yhmtsai** [comment]
@dolokolo The log shows "The length of domain must meet the minimum required length." because it only grab ".eu" in the end.
I am also the beginner to use Caddy with spaceship, so I can only share my CaddyFile.
Hopefully, it can give you some hint for that.

```
*.domain.tld {
        tls {
                dns spaceship <api_key> <api_secret>
        }
}

web1.domain.tld {
        reverse_proxy: ....
}
```

**Comment by dolokolo** [comment]
I figured it out, it was my router redirecting DNS lookups, blocking the DNS lookups to Spaceships DNS servers, hitting root DNS servers instead and falling back to .eu.

Forgot I implemented that a few months back... Made an exception for the proxy VM and its working again :)

**Comment by empressmarissa** [comment]
For anyone still having issues (or again having issues). We now need to explicitly replace libdns/spaceship as well for this to fully work. I also updated both libdns and caddy-dns/spaceship to the latest versions in these releases.

You now need to build caddy yourself in this manner:

```
FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/caddy-dns/spaceship=github.com/empressmarissa/caddy-dns-spaceship@v1.1.1 \
    --replace github.com/libdns/spaceship=github.com/empressmarissa/libdns_spaceship@v1.1.0

FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

@Redth Is anyone still fixing issues with caddy-dns/spaceship and libdns/spaceship?

**Comment by empressmarissa** [comment]
Since the maintainer is not responding, I delved a bit deeper into both libdns-spaceship and caddy-dns-spaceship. I forked both before with the fixes but never fully checked them until now. I'm going to actively maintain my forks from now on:
https://github.com/empressmarissa/libdns_spaceship
https://github.com/empressmarissa/caddy-dns-spaceship

They now do not refer to the unmaintained libraries anymore since I'll be maintaining mine. If you want to use my new version you can:
```
FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/empressmarissa/caddy-dns-spaceship@v1.2.0

FROM caddy:2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

There is no need for replacements anymore. If you encounter any issues with these versions, please head over to my github repo's and make an issue, I'll fix it asap.
